$CPAN::Config = {
                  'yaml_load_code' => '0',
                  'ftp' => '',
                  'term_ornaments' => '1',
                  'ncftp' => '',
                  'use_sqlite' => '0',
                  'mbuild_install_arg' => '',
                  'term_is_latin' => '1',
                  'prefer_external_tar' => '1',
                  'make_install_make_command' => '',
                  'cpan_home' => '/root/.cpan',
                  'inactivity_timeout' => '0',
                  'inhibit_startup_message' => '0',
                  'scan_cache' => 'atstart',
                  'trust_test_report_history' => '0',
                  'show_zero_versions' => '0',
                  'build_dir' => '/root/.cpan/build',
                  'tar_verbosity' => 'none',
                  'wget' => '',
                  'makepl_arg' => 'INSTALLDIRS=site',
                  'connect_to_internet_ok' => '1',
                  'keep_source_where' => '/root/.cpan/sources',
                  'prerequisites_policy' => 'follow',
                  'patch' => '/usr/bin/patch',
                  'cache_metadata' => '1',
                  'yaml_module' => 'YAML',
                  'build_cache' => '100',
                  'applypatch' => '',
                  'make_arg' => '',
                  'build_requires_install_policy' => 'yes',
                  'make_install_arg' => '',
                  'mbuildpl_arg' => '--installdirs site',
                  'test_report' => '0',
                  'pager' => '/usr/bin/less',
                  'tar' => '/bin/tar',
                  'show_upload_date' => '0',
                  'load_module_verbosity' => 'none',
                  'curl' => '',
                  'ftp_proxy' => '',
                  'perl5lib_verbosity' => 'none',
                  'mbuild_arg' => '',
                  'http_proxy' => '',
                  'prefs_dir' => '/root/.cpan/prefs',
                  'build_dir_reuse' => '0',
                  'gzip' => '/bin/gzip',
                  'check_sigs' => '0',
                  'gpg' => '/usr/bin/gpg',
                  'colorize_output' => '0',
                  'getcwd' => 'cwd',
                  'unzip' => '',
                  'histfile' => '/root/.cpan/histfile',
                  'ncftpget' => '',
                  'lynx' => '',
                  'prefer_installer' => 'MB',
                  'urllist' => [
                                 'http://cpan.nautile.nc/CPAN/',
                                 'http://cpan.mirror.uber.com.au/',
                                 'http://cpan.catalyst.net.nz/CPAN/'
                               ],
                  'shell' => undef,
                  'index_expire' => '1',
                  'make' => '',
                  'histsize' => '100',
                  'version_timeout' => '15',
                  'bzip2' => '/bin/bzip2',
                  'auto_commit' => '0',
                  'mbuild_install_build_command' => './Build',
                  'no_proxy' => '',
                  'show_unparsable_versions' => '0',
                  'ftp_passive' => '1',
                  'commandnumber_in_prompt' => '1',
                  'halt_on_failure' => '0'
                };

1;
__END__

